#
# copiar este archivo con el nombre docker-compose.override.yml en el mismo directorio
# si es necesario, configurar valores según necesidad de cada uno.
# ==============================================================================================================

version: '3'
services:
  app:
    environment:
      VIRTUAL_HOST: admin.ypunto.loc
      DEBUG: 1
    networks:
      - default
      - proxy

networks:
  proxy:
    external:
      name: nginx-proxy

